export const PRISMA_PET_STATUS = {
  AVAILABLE: 'AVAILABLE',
  NEW: 'NEW',
  RESERVED: 'RESERVED',
  ADOPTION_IN_PROGRESS: 'ADOPTION_IN_PROGRESS',
  ADOPTED: 'ADOPTED',
  UNAVAILABLE: 'UNAVAILABLE',
  HIDDEN: 'HIDDEN',
} as const

export const PRISMA_PET_PUBLIC_STATUS = {
  PUBLISHED: 'PUBLISHED',
  DRAFT: 'DRAFT',
  HIDDEN: 'HIDDEN',
  RESERVED: 'RESERVED',
  ADOPTED: 'ADOPTED',
} as const

export type PrismaPetStatusValue =
  (typeof PRISMA_PET_STATUS)[keyof typeof PRISMA_PET_STATUS]