export const PRISMA_CASE_TYPE = {
  GENERAL_QUESTION: 'GENERAL_QUESTION',
  PET_QUESTION: 'PET_QUESTION',
  ADOPTION_APPLICATION: 'ADOPTION_APPLICATION',
  VIRTUAL_ADOPTION: 'VIRTUAL_ADOPTION',
  DONATION_SUPPORT: 'DONATION_SUPPORT',
  VOLUNTEER_APPLICATION: 'VOLUNTEER_APPLICATION',
  EVENT_FOLLOWUP: 'EVENT_FOLLOWUP',
  SURRENDER_REQUEST: 'SURRENDER_REQUEST',
  LOST_AND_FOUND: 'LOST_AND_FOUND',
  MEDICAL_UPDATE: 'MEDICAL_UPDATE',
  OTHER: 'OTHER',
} as const

export const PRISMA_CASE_SCOPE = {
  PET_RELATED: 'PET_RELATED',
  GENERAL: 'GENERAL',
} as const

export const PRISMA_CASE_STATUS = {
  OPEN: 'OPEN',
} as const

export const PRISMA_CASE_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const

export const PRISMA_CONTACT_CHANNEL = {
  WEBSITE_FORM: 'WEBSITE_FORM',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  WALK_IN: 'WALK_IN',
  SHELTER_EVENT: 'SHELTER_EVENT',
  ADMIN_CREATED: 'ADMIN_CREATED',
  INTERNAL: 'INTERNAL',
} as const

export const PRISMA_INTERACTION_DIRECTION = {
  INBOUND: 'INBOUND',
  INTERNAL: 'INTERNAL',
} as const

export const PRISMA_REFERENCE_SYSTEM = {
  EMAIL_CLIENT: 'EMAIL_CLIENT',
  CALL_RECORDING: 'CALL_RECORDING',
  WEBSITE: 'WEBSITE',
  MANUAL: 'MANUAL',
  EVENT_SIGNUP: 'EVENT_SIGNUP',
} as const

export const PRISMA_REFERENCE_TYPE = {
  EMAIL: 'EMAIL',
  CALL: 'CALL',
  FORM_SUBMISSION: 'FORM_SUBMISSION',
  CONVERSATION: 'CONVERSATION',
  MANUAL_NOTE: 'MANUAL_NOTE',
} as const

export const PRISMA_CASE_EVENT_ACTOR_TYPE = {
  STAFF: 'STAFF',
} as const

export const PRISMA_PERSON_PROFILE_TYPE = {
  ADOPTER: 'ADOPTER',
  VOLUNTEER: 'VOLUNTEER',
  DONOR: 'DONOR',
  GENERAL_CONTACT: 'GENERAL_CONTACT',
} as const

export const PRISMA_VIRTUAL_ADOPTION_STATUS = {
  ACTIVE: 'ACTIVE',
} as const

export const PRISMA_PAYMENT_FREQUENCY = {
  ONE_TIME: 'ONE_TIME',
  MONTHLY: 'MONTHLY',
} as const

export const PRISMA_DONATION_INQUIRY_TYPE = {
  OTHER: 'OTHER',
} as const

export const PRISMA_VOLUNTEER_APPLICATION_STATUS = {
  NEW: 'NEW',
} as const

export const PRISMA_BACKGROUND_CHECK_STATUS = {
  PENDING: 'PENDING',
} as const

export type PrismaCaseTypeValue =
  (typeof PRISMA_CASE_TYPE)[keyof typeof PRISMA_CASE_TYPE]
export type PrismaCasePriorityValue =
  (typeof PRISMA_CASE_PRIORITY)[keyof typeof PRISMA_CASE_PRIORITY]
export type PrismaContactChannelValue =
  (typeof PRISMA_CONTACT_CHANNEL)[keyof typeof PRISMA_CONTACT_CHANNEL]
export type PrismaReferenceSystemValue =
  (typeof PRISMA_REFERENCE_SYSTEM)[keyof typeof PRISMA_REFERENCE_SYSTEM]
export type PrismaReferenceTypeValue =
  (typeof PRISMA_REFERENCE_TYPE)[keyof typeof PRISMA_REFERENCE_TYPE]
