export const PRISMA_CASE_STATUS = {
  NEW: 'NEW',
  OPEN: 'OPEN',
  WAITING_ON_CONTACT: 'WAITING_ON_CONTACT',
  WAITING_ON_STAFF: 'WAITING_ON_STAFF',
  SCREENING: 'SCREENING',
  SCHEDULED: 'SCHEDULED',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  NO_RESPONSE: 'NO_RESPONSE',
} as const

export const PRISMA_CASE_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const

export const PRISMA_CONTACT_CHANNEL = {
  WEBSITE_FORM: 'WEBSITE_FORM',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  WALK_IN: 'WALK_IN',
  SHELTER_EVENT: 'SHELTER_EVENT',
  ADMIN_CREATED: 'ADMIN_CREATED',
  INTERNAL: 'INTERNAL',
} as const

export const PRISMA_INTERACTION_DIRECTION = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
  INTERNAL: 'INTERNAL',
} as const

export const PRISMA_CASE_EVENT_ACTOR_TYPE = {
  STAFF: 'STAFF',
} as const

export const PRISMA_LANDLORD_APPROVAL = {
  NOT_NEEDED: 'NOT_NEEDED',
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
} as const

export const PRISMA_EXPERIENCE_LEVEL = {
  FIRST_TIME: 'FIRST_TIME',
  SOME_EXPERIENCE: 'SOME_EXPERIENCE',
  EXPERIENCED: 'EXPERIENCED',
} as const

export const PRISMA_VIRTUAL_ADOPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
} as const

export const PRISMA_PAYMENT_FREQUENCY = {
  ONE_TIME: 'ONE_TIME',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  ANNUAL: 'ANNUAL',
} as const

export const PRISMA_DONATION_INQUIRY_TYPE = {
  RECEIPT_REQUEST: 'RECEIPT_REQUEST',
  MONTHLY_DONATION_CHANGE: 'MONTHLY_DONATION_CHANGE',
  CORPORATE_DONATION: 'CORPORATE_DONATION',
  REFUND_OR_CORRECTION: 'REFUND_OR_CORRECTION',
  ALLOCATION_QUESTION: 'ALLOCATION_QUESTION',
  EVENT_SPONSORSHIP: 'EVENT_SPONSORSHIP',
  OTHER: 'OTHER',
} as const

export const PRISMA_VOLUNTEER_APPLICATION_STATUS = {
  NEW: 'NEW',
  SCREENING: 'SCREENING',
  ORIENTATION_SCHEDULED: 'ORIENTATION_SCHEDULED',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const

export const PRISMA_BACKGROUND_CHECK_STATUS = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  CLEARED: 'CLEARED',
  FAILED: 'FAILED',
} as const

export type PrismaCaseStatusValue =
  (typeof PRISMA_CASE_STATUS)[keyof typeof PRISMA_CASE_STATUS]
export type PrismaCasePriorityValue =
  (typeof PRISMA_CASE_PRIORITY)[keyof typeof PRISMA_CASE_PRIORITY]
export type PrismaContactChannelValue =
  (typeof PRISMA_CONTACT_CHANNEL)[keyof typeof PRISMA_CONTACT_CHANNEL]
export type PrismaInteractionDirectionValue =
  (typeof PRISMA_INTERACTION_DIRECTION)[keyof typeof PRISMA_INTERACTION_DIRECTION]
export type PrismaLandlordApprovalValue =
  (typeof PRISMA_LANDLORD_APPROVAL)[keyof typeof PRISMA_LANDLORD_APPROVAL]
export type PrismaExperienceLevelValue =
  (typeof PRISMA_EXPERIENCE_LEVEL)[keyof typeof PRISMA_EXPERIENCE_LEVEL]
export type PrismaVirtualAdoptionStatusValue =
  (typeof PRISMA_VIRTUAL_ADOPTION_STATUS)[keyof typeof PRISMA_VIRTUAL_ADOPTION_STATUS]
export type PrismaPaymentFrequencyValue =
  (typeof PRISMA_PAYMENT_FREQUENCY)[keyof typeof PRISMA_PAYMENT_FREQUENCY]
export type PrismaDonationInquiryTypeValue =
  (typeof PRISMA_DONATION_INQUIRY_TYPE)[keyof typeof PRISMA_DONATION_INQUIRY_TYPE]
export type PrismaVolunteerApplicationStatusValue =
  (typeof PRISMA_VOLUNTEER_APPLICATION_STATUS)[keyof typeof PRISMA_VOLUNTEER_APPLICATION_STATUS]
export type PrismaBackgroundCheckStatusValue =
  (typeof PRISMA_BACKGROUND_CHECK_STATUS)[keyof typeof PRISMA_BACKGROUND_CHECK_STATUS]
